const seedProjects=[{id:'p1',name:'Platforma Northstar',code:'CC-1042',budget:75000},{id:'p2',name:'Ekspansja sprzedaży',code:'CC-1078',budget:40000},{id:'p3',name:'Odświeżenie marki',code:'CC-1103',budget:25000}];
const store={get:(k,f)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(f)),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let projects=store.get('ll-projects',seedProjects), invoices=store.get('ll-invoices',[]), currentFilter='all', currency=store.get('ll-currency','PLN');
const fmt=n=>new Intl.NumberFormat('pl-PL',{style:'currency',currency}).format(n||0);
const esc=s=>String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function project(id){return projects.find(p=>p.id===id)} function spend(id){return invoices.filter(i=>i.project===id&&i.status==='posted').reduce((s,i)=>s+Number(i.amount),0)}
function save(){store.set('ll-projects',projects);store.set('ll-invoices',invoices);render()}
function render(){const total=invoices.filter(i=>i.status==='posted').reduce((s,i)=>s+Number(i.amount),0), budget=projects.reduce((s,p)=>s+Number(p.budget),0), pending=invoices.filter(i=>i.status==='review');
 document.querySelector('#invoiceCount').textContent=invoices.length;document.querySelector('#monthSpend').textContent=fmt(total);document.querySelector('#monthSpendSub').textContent=total?`${invoices.filter(i=>i.status==='posted').length} zaksięgowanych faktur`:'Brak zarejestrowanych kosztów';document.querySelector('#pendingCount').textContent=pending.length;document.querySelector('#activeProjects').textContent=projects.length;document.querySelector('#budgetUsed').textContent=budget?`${Math.round(total/budget*100)}%`:'0%';document.querySelector('#budgetSub').textContent=`${fmt(total)} z ${fmt(budget)} przydzielono`;
 document.querySelector('#spendChart').className='spend-chart'+(projects.length?'':' empty-state');document.querySelector('#spendChart').innerHTML=projects.length?projects.map(p=>{let n=spend(p.id);return `<div class="chart-row"><span>${esc(p.name)}</span><div class="bar-bg"><div class="bar" style="width:${Math.min(100,n/p.budget*100||0)}%"></div></div><span class="chart-amount">${fmt(n)}</span></div>`}).join(''):'Dodaj projekt i zaksięguj fakturę, aby zobaczyć podział kosztów.';
 document.querySelector('#attentionList').className='attention'+(!pending.length?' empty-state':'');document.querySelector('#attentionList').innerHTML=pending.length?pending.slice(0,3).map(i=>`<div class="attention-row"><span><strong>${esc(i.supplier)}</strong><small>${esc(i.number)} · ${fmt(i.amount)}</small></span><span class="pill review">SPRAWDŹ</span></div>`).join(''):'Nie masz faktur do weryfikacji.';
 const rows=invoices.slice().reverse().map(row).join('')||'<tr><td colspan="5" class="empty-state">Brak faktur — zeskanuj pierwszą, aby rozpocząć.</td></tr>';document.querySelector('#recentInvoices').innerHTML=rows;renderInvoices();
 document.querySelector('#projectCards').innerHTML=projects.map(p=>{let n=spend(p.id),pc=Math.min(100,Math.round(n/p.budget*100)||0),actions=currentUser?.role==='admin'?`<button class="delete-project" data-project-id="${p.id}">Usuń projekt</button>`:'';return `<article class="project-card"><span class="code">${esc(p.code)}</span><h3>${esc(p.name)}</h3><div class="budget-line"><span>Wykorzystanie budżetu</span><b>${pc}%</b></div><div class="progress"><i style="width:${pc}%"></i></div><small>${fmt(n)} z ${fmt(p.budget)} zaksięgowano</small>${actions}</article>`}).join('');
 document.querySelector('#budgetReport').innerHTML=projects.map(p=>{let n=spend(p.id),pc=Math.min(100,Math.round(n/p.budget*100)||0);return `<div class="budget-row"><div><b>${esc(p.name)}</b><small>${fmt(n)} / ${fmt(p.budget)}</small></div><div class="progress"><i style="width:${pc}%"></i></div></div>`}).join('')||'<p class="muted">Brak utworzonych projektów.</p>';document.querySelector('#costSummary').innerHTML=`<div><dt>Zaksięgowane koszty</dt><dd>${fmt(total)}</dd></div><div><dt>Do weryfikacji</dt><dd>${fmt(pending.reduce((s,i)=>s+Number(i.amount),0))}</dd></div><div><dt>Łączny budżet projektów</dt><dd>${fmt(budget)}</dd></div><div><dt>Pozostały budżet</dt><dd>${fmt(budget-total)}</dd></div>`;
}
function row(i,admin=false){let p=project(i.project),status=i.status==='posted'?'ZAKSIĘGOWANA':'DO WERYFIKACJI';return `<tr><td>${esc(i.number)}</td>${admin?`<td>${esc(i.supplier)}</td>`:''}<td>${p?`${esc(p.name)} <span class="mono">${esc(p.code)}</span>`:'—'}</td><td>${i.date||'—'}</td><td class="mono">${fmt(i.amount)}</td><td><span class="pill ${i.status}">${status}</span></td>${admin?'<td>⋮</td>':''}</tr>`}
function renderInvoices(){let query=document.querySelector('#invoiceSearch').value.toLowerCase();let list=invoices.filter(i=>(currentFilter==='all'||i.status===currentFilter)&&(`${i.supplier} ${i.number}`).toLowerCase().includes(query));document.querySelector('#invoiceTable').innerHTML=list.length?list.slice().reverse().map(i=>row(i,true)).join(''):'<tr><td colspan="7" class="empty-state">Brak faktur pasujących do tego widoku.</td></tr>'}
function openInvoice(){document.querySelector('#invoiceForm').reset();let sel=document.querySelector('#projectSelect');sel.innerHTML='<option value="">Wybierz projekt / centrum kosztów</option>'+projects.map(p=>`<option value="${p.id}">${esc(p.name)} — ${esc(p.code)}</option>`).join('');document.querySelector('#fileLabel').textContent='PNG, JPG lub PDF — OCR działa w przeglądarce';document.querySelector('#ocrStatus').textContent='';document.querySelector('#invoiceModal').showModal()}
document.querySelector('#scanButton').onclick=openInvoice;document.querySelector('#chooseFile').onclick=()=>document.querySelector('#fileInput').click();
document.querySelector('#fileInput').onchange=async e=>{let file=e.target.files[0];if(!file)return;document.querySelector('#fileLabel').textContent=file.name;let status=document.querySelector('#ocrStatus');if(!file.type.startsWith('image/')){status.textContent='Dodano PDF. W tym MVP wpisz dane ręcznie.';return}if(!window.Tesseract){status.textContent='Biblioteka OCR jest niedostępna. Wpisz dane ręcznie.';return}try{status.textContent='Odczytywanie faktury…';let r=await Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')status.textContent=`Odczytywanie faktury… ${Math.round(m.progress*100)}%`}});let text=r.data.text,form=document.querySelector('#invoiceForm');let number=text.match(/(?:invoice|faktura)\s*(?:no|number|nr|#)?\s*[:#-]?\s*([A-Z0-9][A-Z0-9\-/]+)/i),amount=text.match(/(?:total\s*(?:due|amount)?|amount due|razem|kwota)\s*[:€$£\s]*([0-9][0-9,\.]+)/i),date=text.match(/\b(\d{4}[-\/.]\d{1,2}[-\/.]\d{1,2})\b|\b(\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4})\b/);if(number)form.number.value=number[1];if(amount)form.amount.value=amount[1].replace(',','.').replace(/(\.\d{3})\./,'');if(date){let d=date[1]||date[2];let parsed=new Date(d);if(!isNaN(parsed))form.date.value=parsed.toISOString().slice(0,10)}status.textContent='OCR zakończony — sprawdź odczytane pola przed zapisem.'}catch{status.textContent='Nie udało się odczytać obrazu. Wpisz dane ręcznie.'}}
function submitInvoice(status){let form=document.querySelector('#invoiceForm');if(!form.reportValidity())return;let d=Object.fromEntries(new FormData(form));invoices.push({...d,id:crypto.randomUUID(),amount:Number(d.amount),status});document.querySelector('#invoiceModal').close();save()}
document.querySelector('#invoiceForm').addEventListener('submit',e=>{e.preventDefault();submitInvoice('review')});document.querySelector('#postInvoice').onclick=()=>submitInvoice('posted');
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{let v=b.dataset.view;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.querySelector('#pageTitle').textContent=({dashboard:'Dzień dobry, Samir.',invoices:'Rejestr faktur',projects:'Twoje projekty',reports:'Raporty',settings:'Centrum administracyjne'})[v];document.querySelector('#crumb').textContent='PRZESTRZEŃ ROBOCZA / '+({dashboard:'PRZEGLĄD',invoices:'FAKTURY',projects:'PROJEKTY',reports:'RAPORTY',settings:'ADMINISTRACJA'})[v];window.scrollTo(0,0)});
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x===b));renderInvoices()});document.querySelector('#invoiceSearch').oninput=renderInvoices;
document.querySelector('#newProject').onclick=()=>document.querySelector('#projectModal').showModal();document.querySelector('#projectForm').addEventListener('submit',e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));projects.push({...d,id:crypto.randomUUID(),budget:Number(d.budget)});e.target.closest('dialog').close();save()});
document.querySelector('#exportCsv').onclick=()=>{let lines=['Numer faktury,Dostawca,Projekt,Centrum kosztów,Data,Kwota,Status',...invoices.map(i=>[i.number,i.supplier,project(i.project)?.name||'',project(i.project)?.code||'',i.date,i.amount,i.status==='posted'?'Zaksięgowana':'Do weryfikacji'].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))];let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'}));a.download='ledgerlane-faktury.csv';a.click();URL.revokeObjectURL(a.href)};
const defaultUsers=[{id:'u-admin',name:'Samir Ahmed',email:'admin@ledgerlane.local',password:'admin123',role:'admin',active:true}];
let users=store.get('ll-users',defaultUsers), currentUser=store.get('ll-current-user',null);
function renderUsers(){let table=document.querySelector('#userTable');if(!table)return;table.innerHTML=users.map(u=>`<tr><td><b>${esc(u.name)}</b></td><td>${esc(u.email)}</td><td><span class="role ${u.role}">${u.role==='admin'?'Administrator':'Użytkownik'}</span></td><td><span class="pill posted">AKTYWNY</span></td></tr>`).join('')}
function applyAccess(){let admin=currentUser?.role==='admin';document.querySelector('.user strong').textContent=currentUser?.name||'';document.querySelector('.user small').textContent=admin?'Administrator':'Użytkownik';['settings','projects','reports'].forEach(view=>document.querySelector(`[data-view="${view}"]`).style.display=admin?'flex':'none');document.querySelector('#newProject').style.display=admin?'inline-block':'none';if(!admin&&['projects','reports','settings'].some(view=>document.querySelector(`#${view}`).classList.contains('active'))){document.querySelector('[data-view="dashboard"]').click()}document.querySelector('#loginScreen').classList.toggle('hidden',!!currentUser);render();renderUsers();}
document.querySelector('#loginForm').addEventListener('submit',e=>{e.preventDefault();let email=document.querySelector('#loginEmail').value.trim().toLowerCase(),password=document.querySelector('#loginPassword').value;let found=users.find(u=>u.email.toLowerCase()===email&&u.password===password&&u.active);let error=document.querySelector('#loginError');if(!found){error.textContent='Nieprawidłowy adres e-mail lub hasło.';return}currentUser={id:found.id,name:found.name,email:found.email,role:found.role};store.set('ll-current-user',currentUser);error.textContent='';applyAccess()});
document.querySelector('#logoutButton').addEventListener('click',()=>{currentUser=null;localStorage.removeItem('ll-current-user');document.querySelector('#loginPassword').value='';document.querySelector('#loginError').textContent='';applyAccess()});
document.querySelector('#newUser').onclick=()=>document.querySelector('#userModal').showModal();
document.querySelector('#userForm').addEventListener('submit',e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),email=d.email.trim().toLowerCase();if(users.some(u=>u.email.toLowerCase()===email)){alert('Konto z tym adresem e-mail już istnieje.');return}users.push({id:crypto.randomUUID(),name:d.name.trim(),email,password:d.password,role:d.role,active:true});store.set('ll-users',users);e.target.closest('dialog').close();e.target.reset();renderUsers()});
document.querySelector('#projectCards').addEventListener('click',e=>{let button=e.target.closest('.delete-project');if(!button||currentUser?.role!=='admin')return;let id=button.dataset.projectId,p=project(id);if(!p)return;if(!confirm(`Usunąć projekt „${p.name}”? Faktury pozostaną w rejestrze, ale stracą przypisanie do projektu.`))return;projects=projects.filter(item=>item.id!==id);invoices=invoices.map(invoice=>invoice.project===id?{...invoice,project:''}:invoice);save()});
document.querySelector('#currency').value=currency;
document.querySelector('#currency').onchange=e=>{currency=e.target.value;store.set('ll-currency',currency);render()};
// Przyciski zamknięcia nie mogą wysyłać formularza — zamykają wyłącznie swoje okno dialogowe.
document.querySelectorAll('dialog .close, dialog .secondary[value="cancel"]').forEach(button=>{button.type='button';button.addEventListener('click',()=>button.closest('dialog').close())});
render();applyAccess();
